image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y rpm-build

build_rpm:
  stage: build
  script:
    - rpmbuild -ba brace-background.spec
  artifacts:
    paths:
        - build/noarch/brace-background*.rpm
